kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domains-django-test-static
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domains-django-test-media
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: domains-django-test-conf
data:
  HOST: "domains.test.glauca.digital,domains-test-nginx"
  DJANGO_SETTINGS_MODULE: as207960_domains.settings
  EXTERNAL_URL: "https://domains.test.glauca.digital"
  SENTRY_ENVIRONMENT: "test"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: test
  KEYCLOAK_SCOPES: "openid email profile offline_access"
  KEYCLOAK_CLIENT_ID: "domains"
  DB_HOST: "postgres"
  DB_NAME: "domains-test"
  BILLING_URL: "http://billing-nginx-test"
  EPP_PROXY_ADDR: "epp-proxy-test-primary:50051"
  EPP_PROXY_CA: "/ca-cert/ca.pem"
  EMAIL_HOST: "mx.postal.as207960.net"
  EMAIL_HOST_USER: "apikey"
  EMAIL_PORT: "25"
  EMAIL_FROM: "=?UTF-8?q?Glauca=20Domains=20[TEST]?= <domains-test@glauca.digital>"
  GCHAT_PROJECT_ID: "1045619794257"
  GCHAT_SERVICE_ACCOUNT_FILE: "/google-creds/sa.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domains-django-test
  labels:
    app: domains-test
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domains-test
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: domains-test
        part: django
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: domains-django-test-static
        - name: media
          persistentVolumeClaim:
            claimName: domains-django-test-media
        - name: ca-cert
          configMap:
            name: epp-ca
        - name: google-creds
          secret:
            secretName: domains-test-google-creds
      initContainers:
        - name: django
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-test-conf
            - secretRef:
                name: domains-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-test-secret
            - secretRef:
                name: domains-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: domains-test-celery
              prefix: "CELERY_"
      containers:
        - name: gunicorn
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_domains.wsgi:application"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-test-conf
            - secretRef:
                name: domains-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-test-secret
            - secretRef:
                name: domains-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: domains-test-celery
              prefix: "CELERY_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domains-celery-test
  labels:
    app: domains-test
    part: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domains-test
      part: celery
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: domains-test
        part: celery
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: domains-django-test-static
        - name: media
          persistentVolumeClaim:
            claimName: domains-django-test-media
        - name: ca-cert
          configMap:
            name: epp-ca
        - name: google-creds
          secret:
            secretName: domains-test-google-creds
      containers:
        - name: celery
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["celery", "worker", "-A", "as207960_domains", "--loglevel=INFO", "-c", "32"]
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-test-conf
            - secretRef:
                name: domains-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-test-secret
            - secretRef:
                name: domains-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: domains-test-celery
              prefix: "CELERY_"
---
apiVersion: v1
kind: Service
metadata:
  name: domains-django-test
  labels:
    app: domains-test
    part: django
spec:
  selector:
    app: domains-test
    part: django
  ports:
    - port: 8000
      targetPort: 8000