kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domains-django-static
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domains-django-media
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: domains-django-conf
data:
  HOST: domains.as207960.net
  DJANGO_SETTINGS_MODULE: as207960_domains.settings
  EXTERNAL_URL: "https://domains.as207960.net"
  SENTRY_ENVIRONMENT: "prod"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: master
  KEYCLOAK_SCOPES: "openid email profile offline_access"
  KEYCLOAK_CLIENT_ID: "domains"
  DB_HOST: "postgres"
  DB_NAME: "domains"
  BILLING_URL: "https://billing.as207960.net"
  EPP_PROXY_ADDR: "epp-proxy:50051"
  EPP_PROXY_CA: "/ca-cert/ca.pem"
  EMAIL_HOST: "mx.postal.as207960.net"
  EMAIL_HOST_USER: "apikey"
  EMAIL_PORT: "25"
  EMAIL_FROM: "AS207960 Domains <domains@as207960.net>"
  GCHAT_PROJECT_ID: "226795660453"
  GCHAT_SERVICE_ACCOUNT_FILE: "/google-creds/sa.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domains-django
  labels:
    app: domains
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domains
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: domains
        part: django
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: domains-django-static
        - name: media
          persistentVolumeClaim:
            claimName: domains-django-media
        - name: ca-cert
          configMap:
            name: epp-ca
        - name: google-creds
          secret:
            secretName: domains-google-creds
      initContainers:
        - name: django
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-conf
            - secretRef:
                name: domains-db-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-secret
            - secretRef:
                name: domains-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-email
              prefix: "EMAIL_"
      containers:
        - name: gunicorn
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--log-level=debug", "as207960_domains.wsgi:application"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-conf
            - secretRef:
                name: domains-db-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-secret
            - secretRef:
                name: domains-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-email
              prefix: "EMAIL_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-whois-grpc
  labels:
    app: domains
    part: whois
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domains
      part: whois
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: domains
        part: whois
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: domains-django-static
        - name: media
          persistentVolumeClaim:
            claimName: domains-django-media
        - name: ca-cert
          configMap:
            name: epp-ca
        - name: google-creds
          secret:
            secretName: domains-google-creds
      containers:
        - name: grpc
          image: as207960/domains-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py grpcserver -v 2 --traceback"]
          ports:
            - containerPort: 50051
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/ca-cert/"
              name: ca-cert
            - mountPath: "/google-creds/"
              name: google-creds
          envFrom:
            - configMapRef:
                name: domains-django-conf
            - secretRef:
                name: domains-db-creds
              prefix: "DB_"
            - secretRef:
                name: domains-django-secret
            - secretRef:
                name: domains-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: domains-email
              prefix: "EMAIL_"
---
apiVersion: v1
kind: Service
metadata:
  name: domains-django
  labels:
    app: domains
    part: django
spec:
  selector:
    app: domains
    part: django
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: domains-whois-grpc
  labels:
    app: domains
    part: whois
spec:
  selector:
    app: domains
    part: whois
  ports:
    - port: 50051
      targetPort: 50051
