# Generated by Django 3.0.7 on 2020-08-09 19:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import domains.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    replaces = [('domains', '0001_squashed_0009_auto_20200424_2131'), ('domains', '0010_domainregistration_auth_info'), ('domains', '0011_auto_20200427_1322')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)])),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('street_1', models.CharField(max_length=255, verbose_name='Address line 1')),
                ('street_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('street_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 3')),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255)),
                ('country_code', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact addresses',
                'ordering': ['description', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('entity_type', models.PositiveSmallIntegerField(choices=[(0, 'Not set'), (1, 'Unknown entity'), (2, 'UK Limited Company'), (3, 'UK Public Limited Company'), (4, 'UK Partnership'), (5, 'UK Sole Trader'), (6, 'UK Limited Liability Partnership'), (7, 'UK Industrial Provident Registered Company'), (8, 'UK Individual'), (9, 'UK School'), (10, 'UK Registered Charity'), (11, 'UK Government Body'), (12, 'UK Corporation by Royal Charter'), (13, 'UK Statutory Body'), (14, 'Non UK Individual'), (15, 'Non UK Company'), (16, 'Other UK Entity'), (17, 'Other non UK Entity')])),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fax_ext', models.CharField(blank=True, max_length=64, null=True, verbose_name='Fax extension')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_ext', models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone extension')),
                ('trading_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('int_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_contacts', to='domains.ContactAddress', verbose_name='Internationalised address')),
                ('local_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_contacts', to='domains.ContactAddress', verbose_name='Localised address')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='DomainRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('auth_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='ContactRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_contact_id', models.CharField(default=domains.models.make_id, max_length=16)),
                ('registry_id', models.CharField(max_length=255)),
                ('auth_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Contact')),
            ],
            options={
                'verbose_name_plural': 'Contact registries',
                'ordering': ['registry_contact_id'],
            },
        ),
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_server', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registry_id', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['name_server'],
            },
        ),
    ]
