# Generated by Django 3.0.5 on 2020-04-23 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import domains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name_server', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegistration',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(default=domains.models.make_id, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
