# Generated by Django 3.0.5 on 2020-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20200423_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='registry_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameserver',
            name='registry_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
