# Generated by Django 3.0.5 on 2020-04-24 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import domains.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20200423_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('street_1', models.CharField(max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('street_3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='domainregistration',
            options={'ordering': ['domain']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='registry_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not set'), (1, 'Unknown entity'), (2, 'UK Limited Company'), (3, 'UK Public Limited Company'), (4, 'UK Partnership'), (5, 'UK SoleTrader'), (6, 'UK Limited Liability Partnership'), (7, 'UK Industrial Provident Registered Company'), (8, 'UK Individual'), (9, 'UK School'), (10, 'UK Registered Charity'), (11, 'UK Government Body'), (12, 'UK Corporation by Royal Charter'), (13, 'UK Statutory Body'), (14, 'Non UK Individual'), (15, 'Non UK Company'), (16, 'Other UK Entity'), (17, 'Other non UK Entity')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='fax_ext',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='trading_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContactRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_contact_id', models.CharField(default=domains.models.make_id, max_length=16)),
                ('registry_id', models.CharField(max_length=255)),
                ('auth_info', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='int_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_contacts', to='domains.ContactAddress'),
        ),
        migrations.AddField(
            model_name='contact',
            name='local_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='local_contacts', to='domains.ContactAddress'),
            preserve_default=False,
        ),
    ]
