# Generated by Django 3.0.5 on 2020-04-24 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0004_auto_20200424_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not set'), (1, 'Unknown entity'), (2, 'UK Limited Company'), (3, 'UK Public Limited Company'), (4, 'UK Partnership'), (5, 'UK Sole Trader'), (6, 'UK Limited Liability Partnership'), (7, 'UK Industrial Provident Registered Company'), (8, 'UK Individual'), (9, 'UK School'), (10, 'UK Registered Charity'), (11, 'UK Government Body'), (12, 'UK Corporation by Royal Charter'), (13, 'UK Statutory Body'), (14, 'Non UK Individual'), (15, 'Non UK Company'), (16, 'Other UK Entity'), (17, 'Other non UK Entity')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax_ext',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Fax extension'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='int_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_contacts', to='domains.ContactAddress', verbose_name='Internationalised address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='local_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_contacts', to='domains.ContactAddress', verbose_name='Localised address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone extension'),
        ),
    ]
