# Generated by Django 3.0.5 on 2020-04-24 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_auto_20200424_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactregistry',
            name='auth_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
