# Generated by Django 3.0.5 on 2020-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_auto_20200424_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='auth_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
