# Generated by Django 3.0.5 on 2020-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_domainregistration_auth_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'ordering': ['description', 'name'], 'verbose_name_plural': 'Contact addresses'},
        ),
        migrations.AlterModelOptions(
            name='contactregistry',
            options={'ordering': ['registry_contact_id'], 'verbose_name_plural': 'Contact registries'},
        ),
        migrations.AlterModelOptions(
            name='nameserver',
            options={'ordering': ['name_server']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax_ext',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Fax extension'),
        ),
    ]
