# Generated by Django 3.0.5 on 2020-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_auto_20200427_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not set'), (1, 'Unknown entity'), (2, 'UK Limited Company'), (3, 'UK Public Limited Company'), (4, 'UK Partnership'), (5, 'UK Sole Trader'), (6, 'UK Limited Liability Partnership'), (7, 'UK Industrial Provident Registered Company'), (8, 'UK Individual'), (9, 'UK School'), (10, 'UK Registered Charity'), (11, 'UK Government Body'), (12, 'UK Corporation by Royal Charter'), (13, 'UK Statutory Body'), (31, 'UK Political party'), (14, 'Other UK Entity'), (15, 'Finnish Individual'), (16, 'Finnish Company'), (17, 'Finnish Association'), (18, 'Finnish Institution'), (19, 'Finnish Political Party'), (20, 'Finnish Municipality'), (21, 'Finnish Government'), (22, 'Finnish Public Community'), (23, 'Other Individual'), (24, 'Other Company'), (25, 'Other Association'), (26, 'Other Institution'), (27, 'Other Political Party'), (28, 'Other Municipality'), (29, 'Other Government'), (30, 'Other Public Community')]),
        ),
    ]
