# Generated by Django 3.0.6 on 2020-05-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0014_auto_20200428_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='admin_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_admin', to='domains.Contact'),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='billing_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_billing', to='domains.Contact'),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='pending',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='registrant_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_registrant', to='domains.Contact'),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='tech_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_tech', to='domains.Contact'),
        ),
    ]
