# Generated by Django 3.0.6 on 2020-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0015_auto_20200522_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='disclose_email',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_fax',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_phone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='disclose_address',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='disclose_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='disclose_organisation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
