# Generated by Django 3.0.7 on 2020-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0020_contact_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserver',
            name='resource_id',
            field=models.UUIDField(null=True),
        ),
    ]
