# Generated by Django 3.0.7 on 2020-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0021_nameserver_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='resource_id',
            field=models.UUIDField(null=True),
        ),
    ]
