# Generated by Django 3.0.7 on 2020-06-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0022_domainregistration_resource_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='domainregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nameserver',
            name='user',
        ),
    ]
