# Generated by Django 3.0.7 on 2020-06-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0026_auto_20200624_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangoutsuserlinkstate',
            name='linked',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hangoutsuserlinkstate',
            name='message_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
