# Generated by Django 3.0.7 on 2020-07-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0028_auto_20200624_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdomaintransfer',
            name='user',
        ),
        migrations.AddField(
            model_name='pendingdomaintransfer',
            name='resource_id',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='DomainRegistrationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('period_unit', models.PositiveSmallIntegerField()),
                ('period_value', models.PositiveSmallIntegerField()),
                ('charge_state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_registration_orders_admin', to='domains.Contact')),
                ('billing_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_registration_orders_billing', to='domains.Contact')),
                ('registrant_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_registration_orders_registrant', to='domains.Contact')),
                ('tech_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_registration_orders_tech', to='domains.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
