# Generated by Django 3.0.7 on 2020-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0032_auto_20200717_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaintransferorder',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='domaintransferorder',
            name='user',
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='redirect_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='resource_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='state',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
