# Generated by Django 3.0.7 on 2020-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0033_auto_20200720_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaintransferorder',
            name='task_id',
        ),
    ]
