# Generated by Django 3.0.7 on 2020-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0034_remove_domaintransferorder_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaintransferorder',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('N', 'Needs payment'), ('S', 'Processing'), ('A', 'Pending approval'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
