# Generated by Django 3.0.7 on 2020-07-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0036_auto_20200721_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainregistration',
            name='pending',
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='domain_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.DomainRegistration'),
        ),
        migrations.AlterField(
            model_name='domainreneworder',
            name='domain_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.DomainRegistration'),
        ),
        migrations.AlterField(
            model_name='domainrestoreorder',
            name='domain_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.DomainRegistration'),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='domain_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.DomainRegistration'),
        ),
    ]
