# Generated by Django 3.0.7 on 2020-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0037_auto_20200721_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistrationorder',
            name='off_session',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='domainreneworder',
            name='off_session',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='domainrestoreorder',
            name='off_session',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='domaintransferorder',
            name='off_session',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
