# Generated by Django 3.1 on 2020-08-21 09:02

import as207960_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0038_auto_20200722_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_contact', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_contactaddress', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainregistration', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='auth_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='domain_id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainregistration'),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainregistrationorder', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainreneworder',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainreneworder', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domainreneworder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='domainreneworder',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainrestoreorder',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainrestoreorder', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domainrestoreorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='domainrestoreorder',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='domain_id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domainregistration'),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_domaintransferorder', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangoutsuserlinkstate',
            name='message_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nameserver',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='domains_nameserver', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nameserver',
            name='registry_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nameserver',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
