# Generated by Django 2.2.17 on 2021-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0040_auto_20210116_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
