# Generated by Django 2.2.17 on 2021-02-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0043_domainregistration_former_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='transfer_out_pending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
