# Generated by Django 2.2.17 on 2021-02-21 14:34

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0044_domainregistration_transfer_out_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAutomaticRenewOrder',
            fields=[
                ('state', models.CharField(choices=[('T', 'Started'), ('N', 'Needs payment'), ('S', 'Processing'), ('A', 'Pending approval'), ('C', 'Completed'), ('F', 'Failed')], default='T', max_length=1)),
                ('charge_state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('redirect_uri', models.TextField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('off_session', models.BooleanField(blank=True, default=True)),
                ('id', as207960_utils.models.TypedUUIDField(data_type='domains_domainautoreneworder', primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('period_unit', models.PositiveSmallIntegerField()),
                ('period_value', models.PositiveSmallIntegerField()),
                ('domain_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.DomainRegistration')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
