# Generated by Django 3.1.7 on 2021-03-17 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0046_domainpendingchange_domainpendingchangedsdata_domainpendingchangehostname_domainpendingchangekeydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainpendingchange',
            name='add_host_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='domainpendingchange',
            name='add_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='domainpendingchange',
            name='rem_host_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='domainpendingchange',
            name='rem_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, size=None),
        ),
    ]
