# Generated by Django 3.1.8 on 2021-06-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0046_auto_20210519_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintransferorder',
            name='last_transfer_notify',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
