# Generated by Django 3.1.7 on 2021-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0047_auto_20210317_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpendingchange',
            name='rem_admin_contact',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainpendingchange',
            name='rem_billing_contact',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainpendingchange',
            name='rem_tech_contact',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
