# Generated by Django 3.1.8 on 2021-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0048_webauthnkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='pending_registry_lock_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webauthnkey',
            name='aaguid',
            field=models.UUIDField(verbose_name='AAGUID'),
        ),
        migrations.AlterField(
            model_name='webauthnkey',
            name='pubkey',
            field=models.TextField(verbose_name='Public key'),
        ),
    ]
