# Generated by Django 3.1.7 on 2021-03-19 14:25

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0049_auto_20210317_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='registry_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NameServerAddress',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='domains_nameserveraddress', primary_key=True, serialize=False)),
                ('address_type', models.PositiveSmallIntegerField(choices=[(1, 'IPv4'), (2, 'IPv6')])),
                ('address', models.GenericIPAddressField()),
                ('name_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.nameserver')),
            ],
        ),
    ]
