# Generated by Django 3.1.13 on 2021-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0049_auto_20210713_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainrestoreorder',
            name='period_unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainrestoreorder',
            name='period_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainrestoreorder',
            name='should_renew',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
