# Generated by Django 3.1.7 on 2021-03-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0050_auto_20210319_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserver',
            name='protocol',
            field=models.CharField(choices=[('E', 'EPP'), ('M', 'Manual')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='nameserveraddress',
            name='name_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='domains.nameserver'),
        ),
    ]
