# Generated by Django 3.1.14 on 2023-07-08 11:20

from django.db import migrations, models
import domains.models


def set_defaults(apps, _schema_editor):
    Contact = apps.get_model('domains', 'Contact')
    for contact in Contact.objects.all().iterator():
        contact.handle = domains.models.make_id()
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0050_auto_20210912_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contact',
            name='handle',
            field=models.CharField(default=domains.models.make_id, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='contactregistry',
            name='registry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactregistry',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
