# Generated by Django 5.0.3 on 2024-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0055_contact_eurid_citizenship"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainautomaticreneworder",
            name="resource_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="eurid_citizenship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BE", "België (Belgium)"),
                    ("BG", "България (Bulgaria)"),
                    ("CZ", "Česká republika (Czech Republic)"),
                    ("DE", "Deutschland (Germany)"),
                    ("DK", "Danmark (Denmark)"),
                    ("EE", "Eesti (Estonia)"),
                    ("GR", "Ελλάδα (Greece)"),
                    ("IE", "Éire (Ireland)"),
                    ("ES", "España (Spain)"),
                    ("FR", "France"),
                    ("HR", "Hrvatska (Croatia)"),
                    ("IS", "Ísland (Iceland)"),
                    ("IT", "Italia (Italy)"),
                    ("CY", "Κύπρος (Cyprus)"),
                    ("LT", "Lietuva (Lithuania)"),
                    ("LU", "Lëtzebuerg (Luxembourg)"),
                    ("LV", "Latvija (Latvia)"),
                    ("LI", "Liechtenstein"),
                    ("MT", "Malta"),
                    ("HU", "Magyarország (Hungary)"),
                    ("NL", "Nederland (Netherlands)"),
                    ("NO", "Norge (Norway)"),
                    ("AT", "Österreich (Austria)"),
                    ("PL", "Polska (Poland)"),
                    ("PT", "Portugal"),
                    ("RO", "România (Romania)"),
                    ("FI", "Suomi (Finland)"),
                    ("SE", "Sverige (Sweden)"),
                    ("SI", "Slovenija (Slovenia)"),
                    ("SK", "Slovensko (Slovakia)"),
                ],
                max_length=2,
                null=True,
                verbose_name="EURid citizenship",
            ),
        ),
    ]
