# Generated by Django 5.0.14 on 2026-04-15 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0058_domainregistrationorder_intended_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainautomaticreneworder',
            name='current_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='domainreneworder',
            name='current_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
