# Generated by Django 5.0.14 on 2026-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0059_domainautomaticreneworder_current_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainautomaticreneworder',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='domainregistrationorder',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='domainreneworder',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='domainrestoreorder',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='domaintransferorder',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
