"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class QualifiedLawyer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ACCREDITATION_ID_FIELD_NUMBER: builtins.int
    ACCREDITATION_BODY_FIELD_NUMBER: builtins.int
    ACCREDITATION_YEAR_FIELD_NUMBER: builtins.int
    JURISDICTION_COUNTRY_FIELD_NUMBER: builtins.int
    JURISDICTION_PROVINCE_FIELD_NUMBER: builtins.int
    accreditation_id: typing.Text = ...
    accreditation_body: typing.Text = ...
    accreditation_year: builtins.int = ...
    jurisdiction_country: typing.Text = ...

    @property
    def jurisdiction_province(self) -> google.protobuf.wrappers_pb2.StringValue: ...

    def __init__(self,
        *,
        accreditation_id : typing.Text = ...,
        accreditation_body : typing.Text = ...,
        accreditation_year : builtins.int = ...,
        jurisdiction_country : typing.Text = ...,
        jurisdiction_province : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"jurisdiction_province",b"jurisdiction_province"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"accreditation_body",b"accreditation_body",u"accreditation_id",b"accreditation_id",u"accreditation_year",b"accreditation_year",u"jurisdiction_country",b"jurisdiction_country",u"jurisdiction_province",b"jurisdiction_province"]) -> None: ...
global___QualifiedLawyer = QualifiedLawyer
