# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact/qualified_lawyer/qualified_lawyer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/contact/qualified_lawyer/qualified_lawyer.proto\x12\x1c\x65pp.contact.qualified_lawyer\x1a\x1egoogle/protobuf/wrappers.proto\"\xbe\x01\n\x0fQualifiedLawyer\x12\x18\n\x10\x61\x63\x63reditation_id\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63\x63reditation_body\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63\x63reditation_year\x18\x03 \x01(\x05\x12\x1c\n\x14jurisdiction_country\x18\x04 \x01(\t\x12;\n\x15jurisdiction_province\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValueBCZAgithub.com/as207960/epp-proxy/gen/go/epp/contact/qualified_lawyerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact.qualified_lawyer.qualified_lawyer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAgithub.com/as207960/epp-proxy/gen/go/epp/contact/qualified_lawyer'
  _QUALIFIEDLAWYER._serialized_start=114
  _QUALIFIEDLAWYER._serialized_end=304
# @@protoc_insertion_point(module_scope)
