# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from google.protobuf.wrappers_pb2 import (
    BoolValue as google___protobuf___wrappers_pb2___BoolValue,
    Int64Value as google___protobuf___wrappers_pb2___Int64Value,
    StringValue as google___protobuf___wrappers_pb2___StringValue,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

EventActionValue = typing___NewType('EventActionValue', builtin___int)
type___EventActionValue = EventActionValue
class EventAction(object):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> EventActionValue: ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List[EventActionValue]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, EventActionValue]]: ...
    EventRegistration = typing___cast(EventActionValue, 0)
    EventReregistration = typing___cast(EventActionValue, 1)
    EventLastChanged = typing___cast(EventActionValue, 2)
    EventExpiration = typing___cast(EventActionValue, 3)
    EventDeletion = typing___cast(EventActionValue, 4)
    EventReinstantiation = typing___cast(EventActionValue, 5)
    EventTransfer = typing___cast(EventActionValue, 6)
    EventLocked = typing___cast(EventActionValue, 7)
    EventUnlocked = typing___cast(EventActionValue, 8)
    EventRegistrarExpiration = typing___cast(EventActionValue, 9)
    EventLastUpdateOfRDAP = typing___cast(EventActionValue, 10)
EventRegistration = typing___cast(EventActionValue, 0)
EventReregistration = typing___cast(EventActionValue, 1)
EventLastChanged = typing___cast(EventActionValue, 2)
EventExpiration = typing___cast(EventActionValue, 3)
EventDeletion = typing___cast(EventActionValue, 4)
EventReinstantiation = typing___cast(EventActionValue, 5)
EventTransfer = typing___cast(EventActionValue, 6)
EventLocked = typing___cast(EventActionValue, 7)
EventUnlocked = typing___cast(EventActionValue, 8)
EventRegistrarExpiration = typing___cast(EventActionValue, 9)
EventLastUpdateOfRDAP = typing___cast(EventActionValue, 10)
type___EventAction = EventAction

EntityRoleValue = typing___NewType('EntityRoleValue', builtin___int)
type___EntityRoleValue = EntityRoleValue
class EntityRole(object):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> EntityRoleValue: ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List[EntityRoleValue]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, EntityRoleValue]]: ...
    RoleRegistrant = typing___cast(EntityRoleValue, 0)
    RoleTechnical = typing___cast(EntityRoleValue, 1)
    RoleAdministrative = typing___cast(EntityRoleValue, 2)
    RoleAbuse = typing___cast(EntityRoleValue, 3)
    RoleBilling = typing___cast(EntityRoleValue, 4)
    RoleRegistrar = typing___cast(EntityRoleValue, 5)
    RoleReseller = typing___cast(EntityRoleValue, 6)
    RoleSponsor = typing___cast(EntityRoleValue, 7)
    RoleProxy = typing___cast(EntityRoleValue, 8)
    RoleNotifications = typing___cast(EntityRoleValue, 9)
    RoleNOC = typing___cast(EntityRoleValue, 10)
RoleRegistrant = typing___cast(EntityRoleValue, 0)
RoleTechnical = typing___cast(EntityRoleValue, 1)
RoleAdministrative = typing___cast(EntityRoleValue, 2)
RoleAbuse = typing___cast(EntityRoleValue, 3)
RoleBilling = typing___cast(EntityRoleValue, 4)
RoleRegistrar = typing___cast(EntityRoleValue, 5)
RoleReseller = typing___cast(EntityRoleValue, 6)
RoleSponsor = typing___cast(EntityRoleValue, 7)
RoleProxy = typing___cast(EntityRoleValue, 8)
RoleNotifications = typing___cast(EntityRoleValue, 9)
RoleNOC = typing___cast(EntityRoleValue, 10)
type___EntityRole = EntityRole

StatusValue = typing___NewType('StatusValue', builtin___int)
type___StatusValue = StatusValue
class Status(object):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> StatusValue: ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List[StatusValue]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, StatusValue]]: ...
    StatusActive = typing___cast(StatusValue, 0)
    StatusValidated = typing___cast(StatusValue, 1)
    StatusRenewProhibited = typing___cast(StatusValue, 2)
    StatusUpdateProhibited = typing___cast(StatusValue, 3)
    StatusTransferProhibited = typing___cast(StatusValue, 4)
    StatusDeleteProhibited = typing___cast(StatusValue, 5)
    StatusProxy = typing___cast(StatusValue, 6)
    StatusPrivate = typing___cast(StatusValue, 7)
    StatusRemoved = typing___cast(StatusValue, 8)
    StatusObscured = typing___cast(StatusValue, 9)
    StatusAssociated = typing___cast(StatusValue, 10)
    StatusInactive = typing___cast(StatusValue, 11)
    StatusLocked = typing___cast(StatusValue, 12)
    StatusPendingCreate = typing___cast(StatusValue, 13)
    StatusPendingRenew = typing___cast(StatusValue, 14)
    StatusPendingTransfer = typing___cast(StatusValue, 15)
    StatusPendingUpdate = typing___cast(StatusValue, 16)
    StatusPendingDelete = typing___cast(StatusValue, 17)
    StatusPendingRestore = typing___cast(StatusValue, 18)
    StatusAddPeriod = typing___cast(StatusValue, 19)
    StatusAutoRenewPeriod = typing___cast(StatusValue, 20)
    StatusRenewPeriod = typing___cast(StatusValue, 21)
    StatusRedemptionPeriod = typing___cast(StatusValue, 22)
    StatusTransferPeriod = typing___cast(StatusValue, 23)
    StatusClientRenewProhibited = typing___cast(StatusValue, 24)
    StatusClientUpdateProhibited = typing___cast(StatusValue, 25)
    StatusClientTransferProhibited = typing___cast(StatusValue, 26)
    StatusClientDeleteProhibited = typing___cast(StatusValue, 27)
    StatusClientHold = typing___cast(StatusValue, 28)
    StatusServerRenewProhibited = typing___cast(StatusValue, 29)
    StatusServerUpdateProhibited = typing___cast(StatusValue, 30)
    StatusServerTransferProhibited = typing___cast(StatusValue, 31)
    StatusServerDeleteProhibited = typing___cast(StatusValue, 32)
    StatusServerHold = typing___cast(StatusValue, 33)
StatusActive = typing___cast(StatusValue, 0)
StatusValidated = typing___cast(StatusValue, 1)
StatusRenewProhibited = typing___cast(StatusValue, 2)
StatusUpdateProhibited = typing___cast(StatusValue, 3)
StatusTransferProhibited = typing___cast(StatusValue, 4)
StatusDeleteProhibited = typing___cast(StatusValue, 5)
StatusProxy = typing___cast(StatusValue, 6)
StatusPrivate = typing___cast(StatusValue, 7)
StatusRemoved = typing___cast(StatusValue, 8)
StatusObscured = typing___cast(StatusValue, 9)
StatusAssociated = typing___cast(StatusValue, 10)
StatusInactive = typing___cast(StatusValue, 11)
StatusLocked = typing___cast(StatusValue, 12)
StatusPendingCreate = typing___cast(StatusValue, 13)
StatusPendingRenew = typing___cast(StatusValue, 14)
StatusPendingTransfer = typing___cast(StatusValue, 15)
StatusPendingUpdate = typing___cast(StatusValue, 16)
StatusPendingDelete = typing___cast(StatusValue, 17)
StatusPendingRestore = typing___cast(StatusValue, 18)
StatusAddPeriod = typing___cast(StatusValue, 19)
StatusAutoRenewPeriod = typing___cast(StatusValue, 20)
StatusRenewPeriod = typing___cast(StatusValue, 21)
StatusRedemptionPeriod = typing___cast(StatusValue, 22)
StatusTransferPeriod = typing___cast(StatusValue, 23)
StatusClientRenewProhibited = typing___cast(StatusValue, 24)
StatusClientUpdateProhibited = typing___cast(StatusValue, 25)
StatusClientTransferProhibited = typing___cast(StatusValue, 26)
StatusClientDeleteProhibited = typing___cast(StatusValue, 27)
StatusClientHold = typing___cast(StatusValue, 28)
StatusServerRenewProhibited = typing___cast(StatusValue, 29)
StatusServerUpdateProhibited = typing___cast(StatusValue, 30)
StatusServerTransferProhibited = typing___cast(StatusValue, 31)
StatusServerDeleteProhibited = typing___cast(StatusValue, 32)
StatusServerHold = typing___cast(StatusValue, 33)
type___Status = Status

class LookupRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    query: typing___Text = ...

    def __init__(self,
        *,
        query : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> LookupRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> LookupRequest: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"query",b"query"]) -> None: ...
type___LookupRequest = LookupRequest

class DomainSearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    ns_name: typing___Text = ...
    ns_ip: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ns_name : typing___Optional[typing___Text] = None,
        ns_ip : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> DomainSearchRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> DomainSearchRequest: ...
    def HasField(self, field_name: typing_extensions___Literal[u"name",b"name",u"ns_ip",b"ns_ip",u"ns_name",b"ns_name",u"query",b"query"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"ns_ip",b"ns_ip",u"ns_name",b"ns_name",u"query",b"query"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"query",b"query"]) -> typing_extensions___Literal["name","ns_name","ns_ip"]: ...
type___DomainSearchRequest = DomainSearchRequest

class EntitySearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    handle: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        handle : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> EntitySearchRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> EntitySearchRequest: ...
    def HasField(self, field_name: typing_extensions___Literal[u"handle",b"handle",u"name",b"name",u"query",b"query"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"handle",b"handle",u"name",b"name",u"query",b"query"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"query",b"query"]) -> typing_extensions___Literal["name","handle"]: ...
type___EntitySearchRequest = EntitySearchRequest

class NameServerSearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    ip: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ip : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> NameServerSearchRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> NameServerSearchRequest: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ip",b"ip",u"name",b"name",u"query",b"query"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ip",b"ip",u"name",b"name",u"query",b"query"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"query",b"query"]) -> typing_extensions___Literal["name","ip"]: ...
type___NameServerSearchRequest = NameServerSearchRequest

class ErrorResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    error_code: builtin___int = ...
    title: typing___Text = ...
    description: typing___Text = ...

    def __init__(self,
        *,
        error_code : typing___Optional[builtin___int] = None,
        title : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ErrorResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ErrorResponse: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"description",b"description",u"error_code",b"error_code",u"title",b"title"]) -> None: ...
type___ErrorResponse = ErrorResponse

class RedirectResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    rdap_uri: typing___Text = ...
    port43: typing___Text = ...

    def __init__(self,
        *,
        rdap_uri : typing___Optional[typing___Text] = None,
        port43 : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> RedirectResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> RedirectResponse: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"port43",b"port43",u"rdap_uri",b"rdap_uri"]) -> None: ...
type___RedirectResponse = RedirectResponse

class DomainResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def success(self) -> type___Domain: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___Domain] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> DomainResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> DomainResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___DomainResponse = DomainResponse

class DomainSearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Domains(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Domain]: ...

        def __init__(self,
            *,
            data : typing___Optional[typing___Iterable[type___Domain]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> DomainSearchResponse.Domains: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> DomainSearchResponse.Domains: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
    type___Domains = Domains


    @property
    def success(self) -> type___DomainSearchResponse.Domains: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___DomainSearchResponse.Domains] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> DomainSearchResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> DomainSearchResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___DomainSearchResponse = DomainSearchResponse

class EntityResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def success(self) -> type___Entity: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___Entity] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> EntityResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> EntityResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___EntityResponse = EntityResponse

class EntitySearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Entities(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Entity]: ...

        def __init__(self,
            *,
            data : typing___Optional[typing___Iterable[type___Entity]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> EntitySearchResponse.Entities: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> EntitySearchResponse.Entities: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
    type___Entities = Entities


    @property
    def success(self) -> type___EntitySearchResponse.Entities: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___EntitySearchResponse.Entities] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> EntitySearchResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> EntitySearchResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___EntitySearchResponse = EntitySearchResponse

class NameServerResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def success(self) -> type___NameServer: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___NameServer] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> NameServerResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> NameServerResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___NameServerResponse = NameServerResponse

class NameServerSearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class NameServers(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___NameServer]: ...

        def __init__(self,
            *,
            data : typing___Optional[typing___Iterable[type___NameServer]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> NameServerSearchResponse.NameServers: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> NameServerSearchResponse.NameServers: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
    type___NameServers = NameServers


    @property
    def success(self) -> type___NameServerSearchResponse.NameServers: ...

    @property
    def redirect(self) -> type___RedirectResponse: ...

    @property
    def error(self) -> type___ErrorResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[type___NameServerSearchResponse.NameServers] = None,
        redirect : typing___Optional[type___RedirectResponse] = None,
        error : typing___Optional[type___ErrorResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> NameServerSearchResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> NameServerSearchResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"error",b"error",u"redirect",b"redirect",u"response",b"response",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response",b"response"]) -> typing_extensions___Literal["success","redirect","error"]: ...
type___NameServerSearchResponse = NameServerSearchResponse

class Event(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    action: type___EventActionValue = ...

    @property
    def date(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def actor(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    def __init__(self,
        *,
        action : typing___Optional[type___EventActionValue] = None,
        date : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        actor : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Event: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Event: ...
    def HasField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"date",b"date"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action",b"action",u"actor",b"actor",u"date",b"date"]) -> None: ...
type___Event = Event

class PublicID(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    type: typing___Text = ...
    identifier: typing___Text = ...

    def __init__(self,
        *,
        type : typing___Optional[typing___Text] = None,
        identifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PublicID: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PublicID: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"identifier",b"identifier",u"type",b"type"]) -> None: ...
type___PublicID = PublicID

class Remark(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    description: typing___Text = ...

    @property
    def title(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    @property
    def type(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    def __init__(self,
        *,
        title : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        type : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        description : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Remark: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Remark: ...
    def HasField(self, field_name: typing_extensions___Literal[u"title",b"title",u"type",b"type"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"description",b"description",u"title",b"title",u"type",b"type"]) -> None: ...
type___Remark = Remark

class jCard(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Property(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class PropertiesEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...
            value: typing___Text = ...

            def __init__(self,
                *,
                key : typing___Optional[typing___Text] = None,
                value : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> jCard.Property.PropertiesEntry: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> jCard.Property.PropertiesEntry: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
        type___PropertiesEntry = PropertiesEntry

        class TextArray(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            data: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

            def __init__(self,
                *,
                data : typing___Optional[typing___Iterable[typing___Text]] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> jCard.Property.TextArray: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> jCard.Property.TextArray: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
        type___TextArray = TextArray

        class Extension(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            type: typing___Text = ...
            value: typing___Text = ...

            def __init__(self,
                *,
                type : typing___Optional[typing___Text] = None,
                value : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> jCard.Property.Extension: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> jCard.Property.Extension: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"type",b"type",u"value",b"value"]) -> None: ...
        type___Extension = Extension

        name: typing___Text = ...
        text: typing___Text = ...
        uri: typing___Text = ...
        boolean: builtin___bool = ...
        integer: builtin___int = ...
        float: builtin___float = ...
        language: typing___Text = ...

        @property
        def properties(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

        @property
        def text_array(self) -> type___jCard.Property.TextArray: ...

        @property
        def date(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

        @property
        def time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

        @property
        def date_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

        @property
        def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

        @property
        def extension(self) -> type___jCard.Property.Extension: ...

        def __init__(self,
            *,
            name : typing___Optional[typing___Text] = None,
            properties : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
            text : typing___Optional[typing___Text] = None,
            uri : typing___Optional[typing___Text] = None,
            text_array : typing___Optional[type___jCard.Property.TextArray] = None,
            date : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
            time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
            date_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
            timestamp : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
            boolean : typing___Optional[builtin___bool] = None,
            integer : typing___Optional[builtin___int] = None,
            float : typing___Optional[builtin___float] = None,
            language : typing___Optional[typing___Text] = None,
            extension : typing___Optional[type___jCard.Property.Extension] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> jCard.Property: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> jCard.Property: ...
        def HasField(self, field_name: typing_extensions___Literal[u"boolean",b"boolean",u"date",b"date",u"date_time",b"date_time",u"extension",b"extension",u"float",b"float",u"integer",b"integer",u"language",b"language",u"text",b"text",u"text_array",b"text_array",u"time",b"time",u"timestamp",b"timestamp",u"uri",b"uri",u"value",b"value"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"boolean",b"boolean",u"date",b"date",u"date_time",b"date_time",u"extension",b"extension",u"float",b"float",u"integer",b"integer",u"language",b"language",u"name",b"name",u"properties",b"properties",u"text",b"text",u"text_array",b"text_array",u"time",b"time",u"timestamp",b"timestamp",u"uri",b"uri",u"value",b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["text","uri","text_array","date","time","date_time","timestamp","boolean","integer","float","language","extension"]: ...
    type___Property = Property


    @property
    def properties(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___jCard.Property]: ...

    def __init__(self,
        *,
        properties : typing___Optional[typing___Iterable[type___jCard.Property]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> jCard: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> jCard: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"properties",b"properties"]) -> None: ...
type___jCard = jCard

class Entity(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    handle: typing___Text = ...
    roles: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___EntityRoleValue] = ...
    statuses: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___StatusValue] = ...

    @property
    def card(self) -> type___jCard: ...

    @property
    def public_ids(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PublicID]: ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Entity]: ...

    @property
    def remarks(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Remark]: ...

    @property
    def events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Event]: ...

    @property
    def port43(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    def __init__(self,
        *,
        handle : typing___Optional[typing___Text] = None,
        card : typing___Optional[type___jCard] = None,
        roles : typing___Optional[typing___Iterable[type___EntityRoleValue]] = None,
        public_ids : typing___Optional[typing___Iterable[type___PublicID]] = None,
        entities : typing___Optional[typing___Iterable[type___Entity]] = None,
        remarks : typing___Optional[typing___Iterable[type___Remark]] = None,
        events : typing___Optional[typing___Iterable[type___Event]] = None,
        statuses : typing___Optional[typing___Iterable[type___StatusValue]] = None,
        port43 : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Entity: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Entity: ...
    def HasField(self, field_name: typing_extensions___Literal[u"card",b"card",u"port43",b"port43"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"card",b"card",u"entities",b"entities",u"events",b"events",u"handle",b"handle",u"port43",b"port43",u"public_ids",b"public_ids",u"remarks",b"remarks",u"roles",b"roles",u"statuses",b"statuses"]) -> None: ...
type___Entity = Entity

class Domain(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class SecDNS(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class DSData(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key_tag: builtin___int = ...
            algorithm: builtin___int = ...
            digest_type: builtin___int = ...
            digest: typing___Text = ...

            def __init__(self,
                *,
                key_tag : typing___Optional[builtin___int] = None,
                algorithm : typing___Optional[builtin___int] = None,
                digest_type : typing___Optional[builtin___int] = None,
                digest : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> Domain.SecDNS.DSData: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Domain.SecDNS.DSData: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"algorithm",b"algorithm",u"digest",b"digest",u"digest_type",b"digest_type",u"key_tag",b"key_tag"]) -> None: ...
        type___DSData = DSData

        class KeyData(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            flags: builtin___int = ...
            protocol: builtin___int = ...
            algorithm: builtin___int = ...
            public_key: typing___Text = ...

            def __init__(self,
                *,
                flags : typing___Optional[builtin___int] = None,
                protocol : typing___Optional[builtin___int] = None,
                algorithm : typing___Optional[builtin___int] = None,
                public_key : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> Domain.SecDNS.KeyData: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Domain.SecDNS.KeyData: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"algorithm",b"algorithm",u"flags",b"flags",u"protocol",b"protocol",u"public_key",b"public_key"]) -> None: ...
        type___KeyData = KeyData


        @property
        def zone_signed(self) -> google___protobuf___wrappers_pb2___BoolValue: ...

        @property
        def delegation_signed(self) -> google___protobuf___wrappers_pb2___BoolValue: ...

        @property
        def max_sig_life(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

        @property
        def ds_data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Domain.SecDNS.DSData]: ...

        @property
        def key_data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Domain.SecDNS.KeyData]: ...

        def __init__(self,
            *,
            zone_signed : typing___Optional[google___protobuf___wrappers_pb2___BoolValue] = None,
            delegation_signed : typing___Optional[google___protobuf___wrappers_pb2___BoolValue] = None,
            max_sig_life : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
            ds_data : typing___Optional[typing___Iterable[type___Domain.SecDNS.DSData]] = None,
            key_data : typing___Optional[typing___Iterable[type___Domain.SecDNS.KeyData]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> Domain.SecDNS: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Domain.SecDNS: ...
        def HasField(self, field_name: typing_extensions___Literal[u"delegation_signed",b"delegation_signed",u"max_sig_life",b"max_sig_life",u"zone_signed",b"zone_signed"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"delegation_signed",b"delegation_signed",u"ds_data",b"ds_data",u"key_data",b"key_data",u"max_sig_life",b"max_sig_life",u"zone_signed",b"zone_signed"]) -> None: ...
    type___SecDNS = SecDNS

    handle: typing___Text = ...
    name: typing___Text = ...
    statuses: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___StatusValue] = ...

    @property
    def events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Event]: ...

    @property
    def name_servers(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___NameServer]: ...

    @property
    def public_ids(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PublicID]: ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Entity]: ...

    @property
    def remarks(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Remark]: ...

    @property
    def port43(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    @property
    def sec_dns(self) -> type___Domain.SecDNS: ...

    def __init__(self,
        *,
        handle : typing___Optional[typing___Text] = None,
        name : typing___Optional[typing___Text] = None,
        events : typing___Optional[typing___Iterable[type___Event]] = None,
        name_servers : typing___Optional[typing___Iterable[type___NameServer]] = None,
        public_ids : typing___Optional[typing___Iterable[type___PublicID]] = None,
        entities : typing___Optional[typing___Iterable[type___Entity]] = None,
        statuses : typing___Optional[typing___Iterable[type___StatusValue]] = None,
        remarks : typing___Optional[typing___Iterable[type___Remark]] = None,
        port43 : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        sec_dns : typing___Optional[type___Domain.SecDNS] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Domain: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Domain: ...
    def HasField(self, field_name: typing_extensions___Literal[u"port43",b"port43",u"sec_dns",b"sec_dns"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entities",b"entities",u"events",b"events",u"handle",b"handle",u"name",b"name",u"name_servers",b"name_servers",u"port43",b"port43",u"public_ids",b"public_ids",u"remarks",b"remarks",u"sec_dns",b"sec_dns",u"statuses",b"statuses"]) -> None: ...
type___Domain = Domain

class NameServer(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    handle: typing___Text = ...
    name: typing___Text = ...
    statuses: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___StatusValue] = ...

    @property
    def events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Event]: ...

    @property
    def ip_addresses(self) -> type___IpAddresses: ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Entity]: ...

    @property
    def remarks(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Remark]: ...

    @property
    def port43(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    def __init__(self,
        *,
        handle : typing___Optional[typing___Text] = None,
        name : typing___Optional[typing___Text] = None,
        events : typing___Optional[typing___Iterable[type___Event]] = None,
        ip_addresses : typing___Optional[type___IpAddresses] = None,
        entities : typing___Optional[typing___Iterable[type___Entity]] = None,
        statuses : typing___Optional[typing___Iterable[type___StatusValue]] = None,
        remarks : typing___Optional[typing___Iterable[type___Remark]] = None,
        port43 : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> NameServer: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> NameServer: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ip_addresses",b"ip_addresses",u"port43",b"port43"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entities",b"entities",u"events",b"events",u"handle",b"handle",u"ip_addresses",b"ip_addresses",u"name",b"name",u"port43",b"port43",u"remarks",b"remarks",u"statuses",b"statuses"]) -> None: ...
type___NameServer = NameServer

class IpAddresses(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    v4: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    v6: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    def __init__(self,
        *,
        v4 : typing___Optional[typing___Iterable[typing___Text]] = None,
        v6 : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> IpAddresses: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> IpAddresses: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"v4",b"v4",u"v6",b"v6"]) -> None: ...
type___IpAddresses = IpAddresses
