"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ChargeState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChargeStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChargeState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _ChargeState.ValueType  # 0
    PENDING: _ChargeState.ValueType  # 1
    PROCESSING: _ChargeState.ValueType  # 2
    FAILED: _ChargeState.ValueType  # 3
    COMPLETED: _ChargeState.ValueType  # 4

class ChargeState(_ChargeState, metaclass=_ChargeStateEnumTypeWrapper): ...

UNKNOWN: ChargeState.ValueType  # 0
PENDING: ChargeState.ValueType  # 1
PROCESSING: ChargeState.ValueType  # 2
FAILED: ChargeState.ValueType  # 3
COMPLETED: ChargeState.ValueType  # 4
global___ChargeState = ChargeState

class _SubscriptionState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SubscriptionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SubscriptionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUB_UNKNOWN: _SubscriptionState.ValueType  # 0
    SUB_PENDING: _SubscriptionState.ValueType  # 1
    SUB_PAST_DUE: _SubscriptionState.ValueType  # 2
    SUB_ACTIVE: _SubscriptionState.ValueType  # 3
    SUB_CANCELLED: _SubscriptionState.ValueType  # 4

class SubscriptionState(_SubscriptionState, metaclass=_SubscriptionStateEnumTypeWrapper): ...

SUB_UNKNOWN: SubscriptionState.ValueType  # 0
SUB_PENDING: SubscriptionState.ValueType  # 1
SUB_PAST_DUE: SubscriptionState.ValueType  # 2
SUB_ACTIVE: SubscriptionState.ValueType  # 3
SUB_CANCELLED: SubscriptionState.ValueType  # 4
global___SubscriptionState = SubscriptionState

@typing_extensions.final
class BillingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONVERT_CURRENCY_FIELD_NUMBER: builtins.int
    CHARGE_USER_FIELD_NUMBER: builtins.int
    @property
    def convert_currency(self) -> global___ConvertCurrencyRequest: ...
    @property
    def charge_user(self) -> global___ChargeUserRequest: ...
    def __init__(
        self,
        *,
        convert_currency: global___ConvertCurrencyRequest | None = ...,
        charge_user: global___ChargeUserRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["charge_user", b"charge_user", "convert_currency", b"convert_currency", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["charge_user", b"charge_user", "convert_currency", b"convert_currency", "message", b"message"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["message", b"message"]) -> typing_extensions.Literal["convert_currency", "charge_user"] | None: ...

global___BillingRequest = BillingRequest

@typing_extensions.final
class ConvertCurrencyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_CURRENCY_FIELD_NUMBER: builtins.int
    TO_CURRENCY_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    REMOTE_IP_FIELD_NUMBER: builtins.int
    COUNTRY_SELECTION_FIELD_NUMBER: builtins.int
    from_currency: builtins.str
    to_currency: builtins.str
    amount: builtins.int
    @property
    def username(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def remote_ip(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def country_selection(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        from_currency: builtins.str = ...,
        to_currency: builtins.str = ...,
        amount: builtins.int = ...,
        username: google.protobuf.wrappers_pb2.StringValue | None = ...,
        remote_ip: google.protobuf.wrappers_pb2.StringValue | None = ...,
        country_selection: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["country_selection", b"country_selection", "remote_ip", b"remote_ip", "username", b"username"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "country_selection", b"country_selection", "from_currency", b"from_currency", "remote_ip", b"remote_ip", "to_currency", b"to_currency", "username", b"username"]) -> None: ...

global___ConvertCurrencyRequest = ConvertCurrencyRequest

@typing_extensions.final
class ConvertCurrencyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    AMOUNT_INC_VAT_FIELD_NUMBER: builtins.int
    TAXABLE_FIELD_NUMBER: builtins.int
    USED_COUNTRY_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    amount: builtins.int
    amount_inc_vat: builtins.int
    taxable: builtins.bool
    used_country: builtins.str
    currency: builtins.str
    def __init__(
        self,
        *,
        amount: builtins.int = ...,
        amount_inc_vat: builtins.int = ...,
        taxable: builtins.bool = ...,
        used_country: builtins.str = ...,
        currency: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "amount_inc_vat", b"amount_inc_vat", "currency", b"currency", "taxable", b"taxable", "used_country", b"used_country"]) -> None: ...

global___ConvertCurrencyResponse = ConvertCurrencyResponse

@typing_extensions.final
class ChargeUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    DESCRIPTOR_FIELD_NUMBER: builtins.int
    CAN_REJECT_FIELD_NUMBER: builtins.int
    OFF_SESSION_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    RETURN_URI_FIELD_NUMBER: builtins.int
    NOTIF_QUEUE_FIELD_NUMBER: builtins.int
    amount: builtins.int
    id: builtins.str
    descriptor: builtins.str
    can_reject: builtins.bool
    off_session: builtins.bool
    user_id: builtins.str
    @property
    def return_uri(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def notif_queue(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        amount: builtins.int = ...,
        id: builtins.str = ...,
        descriptor: builtins.str = ...,
        can_reject: builtins.bool = ...,
        off_session: builtins.bool = ...,
        user_id: builtins.str = ...,
        return_uri: google.protobuf.wrappers_pb2.StringValue | None = ...,
        notif_queue: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["notif_queue", b"notif_queue", "return_uri", b"return_uri"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "can_reject", b"can_reject", "descriptor", b"descriptor", "id", b"id", "notif_queue", b"notif_queue", "off_session", b"off_session", "return_uri", b"return_uri", "user_id", b"user_id"]) -> None: ...

global___ChargeUserRequest = ChargeUserRequest

@typing_extensions.final
class ChargeUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ChargeResult:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ChargeResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChargeUserResponse._ChargeResult.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCESS: ChargeUserResponse._ChargeResult.ValueType  # 0
        FAIL: ChargeUserResponse._ChargeResult.ValueType  # 1
        REDIRECT: ChargeUserResponse._ChargeResult.ValueType  # 2

    class ChargeResult(_ChargeResult, metaclass=_ChargeResultEnumTypeWrapper): ...
    SUCCESS: ChargeUserResponse.ChargeResult.ValueType  # 0
    FAIL: ChargeUserResponse.ChargeResult.ValueType  # 1
    REDIRECT: ChargeUserResponse.ChargeResult.ValueType  # 2

    CHARGE_STATE_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    REDIRECT_URI_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    charge_state_id: builtins.str
    result: global___ChargeUserResponse.ChargeResult.ValueType
    message: builtins.str
    redirect_uri: builtins.str
    state: global___ChargeState.ValueType
    def __init__(
        self,
        *,
        charge_state_id: builtins.str = ...,
        result: global___ChargeUserResponse.ChargeResult.ValueType = ...,
        message: builtins.str = ...,
        redirect_uri: builtins.str = ...,
        state: global___ChargeState.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "message", b"message", "redirect_uri", b"redirect_uri", "state", b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["charge_state_id", b"charge_state_id", "data", b"data", "message", b"message", "redirect_uri", b"redirect_uri", "result", b"result", "state", b"state"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["message", "redirect_uri", "state"] | None: ...

global___ChargeUserResponse = ChargeUserResponse

@typing_extensions.final
class ChargeStateNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHARGE_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    LAST_ERROR_FIELD_NUMBER: builtins.int
    REDIRECT_URL_FIELD_NUMBER: builtins.int
    charge_id: builtins.str
    account: builtins.str
    state: global___ChargeState.ValueType
    @property
    def last_error(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    redirect_url: builtins.str
    def __init__(
        self,
        *,
        charge_id: builtins.str = ...,
        account: builtins.str = ...,
        state: global___ChargeState.ValueType = ...,
        last_error: google.protobuf.wrappers_pb2.StringValue | None = ...,
        redirect_url: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["last_error", b"last_error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "charge_id", b"charge_id", "last_error", b"last_error", "redirect_url", b"redirect_url", "state", b"state"]) -> None: ...

global___ChargeStateNotification = ChargeStateNotification

@typing_extensions.final
class SubscribeUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIAL_USAGE_FIELD_NUMBER: builtins.int
    PLAN_ID_FIELD_NUMBER: builtins.int
    CAN_REJECT_FIELD_NUMBER: builtins.int
    OFF_SESSION_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    RETURN_URI_FIELD_NUMBER: builtins.int
    initial_usage: builtins.int
    plan_id: builtins.str
    can_reject: builtins.bool
    off_session: builtins.bool
    user_id: builtins.str
    @property
    def return_uri(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        initial_usage: builtins.int = ...,
        plan_id: builtins.str = ...,
        can_reject: builtins.bool = ...,
        off_session: builtins.bool = ...,
        user_id: builtins.str = ...,
        return_uri: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["return_uri", b"return_uri"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["can_reject", b"can_reject", "initial_usage", b"initial_usage", "off_session", b"off_session", "plan_id", b"plan_id", "return_uri", b"return_uri", "user_id", b"user_id"]) -> None: ...

global___SubscribeUserRequest = SubscribeUserRequest

@typing_extensions.final
class SubscribeUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SubscriptionResult:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SubscriptionResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SubscribeUserResponse._SubscriptionResult.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCESS: SubscribeUserResponse._SubscriptionResult.ValueType  # 0
        REDIRECT: SubscribeUserResponse._SubscriptionResult.ValueType  # 1

    class SubscriptionResult(_SubscriptionResult, metaclass=_SubscriptionResultEnumTypeWrapper): ...
    SUCCESS: SubscribeUserResponse.SubscriptionResult.ValueType  # 0
    REDIRECT: SubscribeUserResponse.SubscriptionResult.ValueType  # 1

    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    REDIRECT_URI_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    subscription_id: builtins.str
    result: global___SubscribeUserResponse.SubscriptionResult.ValueType
    redirect_uri: builtins.str
    state: global___SubscriptionState.ValueType
    def __init__(
        self,
        *,
        subscription_id: builtins.str = ...,
        result: global___SubscribeUserResponse.SubscriptionResult.ValueType = ...,
        redirect_uri: builtins.str = ...,
        state: global___SubscriptionState.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "redirect_uri", b"redirect_uri", "state", b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "redirect_uri", b"redirect_uri", "result", b"result", "state", b"state", "subscription_id", b"subscription_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["redirect_uri", "state"] | None: ...

global___SubscribeUserResponse = SubscribeUserResponse

@typing_extensions.final
class SubscriptionNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    subscription_id: builtins.str
    state: global___SubscriptionState.ValueType
    def __init__(
        self,
        *,
        subscription_id: builtins.str = ...,
        state: global___SubscriptionState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["state", b"state", "subscription_id", b"subscription_id"]) -> None: ...

global___SubscriptionNotification = SubscriptionNotification
